project.name: rifle

project.repositories:
  - apache-mynewt-core
  - mynewt_arduino_zero

repository.apache-mynewt-core:
  type: github
  vers: 1-latest
  user: apache
  repo: mynewt-core

repository.mynewt_arduino_zero:
  type: github
  vers: 1-latest
  user: runtimeco
  repo: mynewt_arduino_zero
